name: aquaflow
description: "Un prototipo inteligente que te permite monitorear y controlar los par√°metros esenciales de tu piscina desde la palma de tu mano, asegurando un oasis perfecto en todo momento."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: ^12.0.0
  firebase_auth: ^6.1.0
  intl: 0.20.2
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0
  table_calendar: ^3.0.11


flutter:
  uses-material-design: true
  assets:
    - assets/icons/ctrlpool.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/ctrlpool.png
  remove_alpha_ios: true
